#!/bin/bash
# Auto-generated by Claude Cowork on 2026-05-01.
# Double-click in Finder to commit the supabase-as-code changes.
# Safe to delete after successful commit.

set -e
cd "$(dirname "$0")"

echo "==> Removing stale .git/index.lock (if present)..."
rm -f .git/index.lock || true

echo "==> Current branch:"
git rev-parse --abbrev-ref HEAD

# We may already be on feat/supabase-as-code from sandbox; if not, create it.
CURRENT=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT" != "feat/supabase-as-code" ]; then
  echo "==> Creating feat/supabase-as-code branch from current HEAD..."
  git checkout -b feat/supabase-as-code
fi

echo "==> Staging only the files this handover changed..."
git add \
  .env.example \
  .eslintrc.json \
  .github/workflows/ci.yml \
  .github/workflows/supabase-diff.yml \
  README.md \
  package.json \
  package-lock.json \
  supabase/.gitignore \
  supabase/PULL_GAPS.md \
  supabase/README.md \
  supabase/config.toml \
  supabase/seed.sql \
  supabase/functions/.gitkeep \
  docs/15_SUPABASE_ARCHITECTURE.md \
  docs/16_SESSION_HANDOFF.md \
  docs/CONTRIBUTING.md \
  docs/17_DEPLOYMENT_GUIDE.md \
  app/operations/activities/page.tsx \
  components/agents/AgentsHub.tsx

# Tell git the old 15_DEPLOYMENT_GUIDE.md is gone (renamed to 17_)
git add -u docs/15_DEPLOYMENT_GUIDE.md || true

echo "==> Files staged for commit:"
git diff --cached --name-status

echo ""
echo "==> Committing..."
git commit -m "infra: Supabase-as-code + CI + doc sync

- Bootstrap supabase/ folder (config.toml, seed.sql, README, .gitignore, PULL_GAPS, functions/.gitkeep)
- Add .github/workflows/ci.yml (lint + typecheck + build, Node 20)
- Add .github/workflows/supabase-diff.yml (read-only diff comment on PRs touching supabase/migrations/**)
- Strip default password from .env.example (DASHBOARD_PASSWORD=CHANGE_ME)
- Move docs:15_SUPABASE_ARCHITECTURE.md (root, colon-named) into docs/15_SUPABASE_ARCHITECTURE.md
- Renumber docs/15_DEPLOYMENT_GUIDE.md -> 17_DEPLOYMENT_GUIDE.md
- Stub docs/16_SESSION_HANDOFF.md (content import pending)
- Add docs/CONTRIBUTING.md (branching, PR process, migration workflow)
- README: add Status section and Database-changes section
- Add eslint + eslint-config-next devDependencies (CI prerequisite)
- Fix pre-existing typecheck error in app/operations/activities/page.tsx (r30 -> period)
- Fix pre-existing JSX comment-textnode error in components/agents/AgentsHub.tsx

Pending (blocked on TBC-HM org access or Supabase login):
- supabase/migrations/<ts>_initial_schema.sql via 'supabase db pull'
- Push branch + open PR (needs TBC-HM write)
- Branch protection on main (needs admin)
- 14 GitHub Issues (needs repo write)
- SUPABASE_ACCESS_TOKEN / SUPABASE_PROJECT_REF / SUPABASE_DB_PASSWORD secrets (needs admin)
"

echo ""
echo "==> Done. Branch: feat/supabase-as-code"
echo "==> Latest commit:"
git log --oneline -1

echo ""
echo "==> Status of remaining (untouched) dirty files in working tree:"
git status --short | head -20

echo ""
echo "Press Return to close this window."
read -r _
