#!/bin/bash
# Auto-generated by Claude Cowork on 2026-05-01.
# Run AFTER .commit-supabase-as-code.command succeeded.
# This pulls the cloud schema into supabase/migrations/, then verifies parity.

set -e
cd "$(dirname "$0")"

echo "============================================================"
echo "Supabase as-code: pull + verify"
echo "Project: namkhan-pms (kpenyneooigsyuuomgct)"
echo "============================================================"
echo ""

echo "==> Step 1: supabase login"
echo "    A browser window will open. Click 'Authorize'."
echo "    Press Return to start."
read -r _
npx supabase login

echo ""
echo "==> Step 2: link project (asks for DB password)"
echo "    Find it in: Supabase Dashboard > Project Settings > Database > Connection string"
npx supabase link --project-ref kpenyneooigsyuuomgct

echo ""
echo "==> Step 3: db pull (writes initial migration)"
npx supabase db pull

echo ""
echo "==> Step 4: list new migrations"
ls -la supabase/migrations/ | tail -10

echo ""
echo "==> Step 5: verify schemas captured"
LATEST_MIGRATION=$(ls -t supabase/migrations/*.sql | head -1)
echo "    Inspecting: $LATEST_MIGRATION"
echo ""
echo "    Schemas found in migration:"
grep -oE 'CREATE SCHEMA[^;]*' "$LATEST_MIGRATION" | sort -u | head -25
echo ""
echo "    Materialized views found:"
grep -oE 'CREATE MATERIALIZED VIEW [^ ]+' "$LATEST_MIGRATION" | sort -u | head -25
echo ""
echo "    Cron jobs found (should be 14 — if 0, hand-write per docs/15):"
grep -c "cron.schedule" "$LATEST_MIGRATION" || echo "0 — pg_cron leak. Add hand-written migration. See supabase/PULL_GAPS.md"

echo ""
echo "==> Step 6: db diff --linked (must return empty after pull)"
npx supabase db diff --linked || echo "WARNING: diff returned changes. Investigate before committing."

echo ""
echo "==> Step 7: stage migration"
git add supabase/migrations/
git status --short supabase/

echo ""
echo "Done. Review the migration, then commit:"
echo "    git commit -m 'supabase: import initial schema via db pull'"
echo ""
echo "Press Return to close."
read -r _
