// app/operations/staff/_components/OffboardingWizardTab.tsx
//
// PBS 2026-05-15: Offboarding wizard. Pick active employee → jurisdiction-aware
// legal checklist (ES = Spain · LA = Lao) → "Generate termination letter" →
// POST /api/hr/termination-letter → Claude drafts a formal carta de despido (ES)
// or termination letter (LA) → lands in Reports inbox (cockpit_tickets,
// source='agent_delivery', intent='termination_letter').

'use client';

import Panel from '@/components/page/Panel';
import { useState, useTransition } from 'react';
import type { SeniorityBundle, EmployeeWithSeniority } from '@/lib/hr/seniority';

const ES_CHECKLIST: { label: string; critical: boolean; hint: string }[] = [
  { label: 'Carta de despido (formal termination letter)', critical: true,  hint: 'Generated by this wizard · must state cause + effective date · entregada en mano + firmada' },
  { label: 'Finiquito (final settlement)',                  critical: true,  hint: 'Días devengados, vacaciones no disfrutadas, pagas extra prorrateadas' },
  { label: 'Liquidación de indemnización',                  critical: true,  hint: 'See snapshot below — 33d/yr unfair OR 20d/yr objective OR 12d/yr fixed-term' },
  { label: 'TGSS baja (Modelo TA.2/S)',                     critical: true,  hint: 'Comunicar a Seguridad Social · plazo: hasta 3 días naturales · vía Sistema RED' },
  { label: 'Certificado de empresa SEPE',                   critical: true,  hint: 'For unemployment benefit · electronic via Sistema RED · 3 días' },
  { label: 'Modelo 10-T (IRPF) for current year',           critical: false, hint: 'Final IRPF withholding summary' },
  { label: 'Devolución uniforme / llaves / badge / equipos', critical: false, hint: 'Equipment + uniform return checklist' },
  { label: 'NDA / no-competencia reminder',                 critical: false, hint: 'If non-compete clause active · re-issue copy with post-termination scope' },
  { label: 'Convenio Colectivo Hostelería Baleares check',  critical: true,  hint: 'CCT clauses on notice + indemnización supplements · BOIB-aligned' },
];

const LA_CHECKLIST: { label: string; critical: boolean; hint: string }[] = [
  { label: 'Formal termination letter',            critical: true,  hint: 'Stated cause + notice + effective date · signed acknowledgment' },
  { label: 'Notice period verification',           critical: true,  hint: 'Per contract — Lao Labour Law 2014 Art. 82 default 30/45 days' },
  { label: 'End-of-service gratuity (if granted)', critical: false, hint: 'Lao law has NO statutory entitlement — contract may grant it' },
  { label: 'Final pay + unused leave',             critical: true,  hint: 'Last salary + accrued unused annual leave (15 working days/yr default)' },
  { label: 'Personal income tax settlement',       critical: false, hint: 'Cleared via final payslip' },
  { label: 'Equipment + uniform return',           critical: false, hint: 'Keys, radio, uniform, time-clock card' },
  { label: 'Confidentiality reminder',             critical: false, hint: 'NDA clauses survive termination · re-issue copy' },
];

type Reason = 'unfair' | 'objective' | 'fixed_term_end' | 'voluntary' | 'disciplinary';

export default function OffboardingWizardTab({
  propertyId, bundle,
}: {
  propertyId: number;
  bundle: SeniorityBundle;
}) {
  const isDonna = bundle.isDonna;
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [reason, setReason] = useState<Reason>(isDonna ? 'objective' : 'voluntary');
  const [effective, setEffective] = useState<string>(() => new Date().toISOString().slice(0, 10));
  const [pending, startTransition] = useTransition();
  const [result, setResult] = useState<{ ok: boolean; message: string; ticket_id?: number } | null>(null);

  const employee: EmployeeWithSeniority | undefined = bundle.rows.find((r) => r.id === selectedId);
  const checklist = isDonna ? ES_CHECKLIST : LA_CHECKLIST;

  const handleGenerate = () => {
    if (!employee) return;
    setResult(null);
    startTransition(async () => {
      try {
        const res = await fetch('/api/hr/termination-letter', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            property_id: propertyId,
            employee_id: employee.id,
            employee_name: employee.full_name_en,
            position: employee.current_position_code,
            department: employee.current_dept_code,
            hire_date: employee.hire_date,
            monthly_eur: employee.monthly_eur,
            seniority_years: employee.seniorityYears,
            seniority_label: employee.seniorityLabel,
            indem_unfair: employee.indemUnfair,
            indem_objective: employee.indemObjective,
            indem_fixed_end: employee.indemFixedTermEnd,
            contract_type: employee.contract_type,
            reason,
            effective_date: effective,
            jurisdiction: isDonna ? 'ES' : 'LA',
          }),
        });
        const j = await res.json();
        if (res.ok && j.ok) {
          setResult({ ok: true, message: 'Termination letter generated and delivered to Reports inbox.', ticket_id: j.ticket_id });
        } else {
          setResult({ ok: false, message: j.error || `HTTP ${res.status}` });
        }
      } catch (e) {
        setResult({ ok: false, message: e instanceof Error ? e.message : 'Network error' });
      }
    });
  };

  return (
    <>
      <Panel title="1 · Choose employee to offboard" eyebrow={`${bundle.rows.length} active staff · sorted by seniority desc`}>
        <div style={{ padding: 14, display: 'grid', gridTemplateColumns: '2fr 2fr 1fr', gap: 14 }}>
          <label style={{ display: 'flex', flexDirection: 'column', gap: 4, fontSize: 'var(--t-sm)' }}>
            <span style={labelStyle()}>Employee</span>
            <select value={selectedId ?? ''} onChange={(e) => setSelectedId(e.target.value ? Number(e.target.value) : null)} style={inputStyle()}>
              <option value="">— select active employee —</option>
              {bundle.rows.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.full_name_en ?? `#${r.id}`} · {r.current_dept_code ?? '—'} · {r.seniorityLabel}
                </option>
              ))}
            </select>
          </label>
          <label style={{ display: 'flex', flexDirection: 'column', gap: 4, fontSize: 'var(--t-sm)' }}>
            <span style={labelStyle()}>Termination reason</span>
            <select value={reason} onChange={(e) => setReason(e.target.value as Reason)} style={inputStyle()}>
              {isDonna ? (
                <>
                  <option value="objective">Despido objetivo (economic/objective) · 20d/y</option>
                  <option value="unfair">Despido improcedente (unfair) · 33d/y</option>
                  <option value="disciplinary">Despido disciplinario (cause-based) · 0d</option>
                  <option value="fixed_term_end">End of fixed-term contract · 12d/y</option>
                  <option value="voluntary">Voluntary resignation · 0d</option>
                </>
              ) : (
                <>
                  <option value="voluntary">Voluntary resignation</option>
                  <option value="objective">Notice termination · per contract</option>
                  <option value="disciplinary">Disciplinary termination · for cause</option>
                  <option value="fixed_term_end">End of fixed-term contract</option>
                </>
              )}
            </select>
          </label>
          <label style={{ display: 'flex', flexDirection: 'column', gap: 4, fontSize: 'var(--t-sm)' }}>
            <span style={labelStyle()}>Effective date</span>
            <input type="date" value={effective} onChange={(e) => setEffective(e.target.value)} style={inputStyle()} />
          </label>
        </div>
      </Panel>

      {employee && (
        <>
          <Panel
            title={`2 · ${isDonna ? 'Spanish' : 'Lao'} legal checklist`}
            eyebrow={isDonna ? 'CCT Hostelería Baleares · BOIB-aligned · plazos TGSS/SEPE' : 'Lao Labour Law 2014 · Art. 82 notice · gratuity per contract'}
          >
            <div style={{ padding: 14, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
              {checklist.map((c, i) => (
                <div key={i} style={{
                  padding: '8px 10px',
                  background: 'var(--paper)',
                  border: '1px solid var(--paper-deep)',
                  borderLeft: `3px solid ${c.critical ? 'var(--st-bad, #B23B3B)' : 'var(--brass)'}`,
                  borderRadius: 4,
                  fontSize: 'var(--t-sm)',
                }}>
                  <div style={{ fontWeight: 600, color: 'var(--ink)' }}>
                    {c.critical && <span style={{ color: 'var(--st-bad, #B23B3B)', marginRight: 6 }}>●</span>}
                    {c.label}
                  </div>
                  <div style={{ marginTop: 2, fontSize: 'var(--t-xs)', color: 'var(--ink-mute)' }}>{c.hint}</div>
                </div>
              ))}
            </div>
          </Panel>

          <Panel title="3 · Employee snapshot" eyebrow="Figures the letter will quote">
            <div style={{ padding: 14, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 10, fontSize: 'var(--t-sm)' }}>
              <SnapshotField label="Name"          value={employee.full_name_en ?? '—'} />
              <SnapshotField label="Department"    value={employee.current_dept_code ?? '—'} />
              <SnapshotField label="Position"      value={employee.current_position_code ?? '—'} />
              <SnapshotField label="Hire date"     value={employee.hire_date ?? '—'} />
              <SnapshotField label="Seniority"     value={employee.seniorityLabel} />
              <SnapshotField label="Contract"      value={employee.contract_type ?? '—'} />
              {isDonna && <SnapshotField label="Monthly €" value={employee.monthly_eur > 0 ? `€${Math.round(employee.monthly_eur).toLocaleString('en-US')}` : '—'} />}
              {isDonna && <SnapshotField label={`Indemnización · ${reason}`} value={resolveIndem(employee, reason)} />}
            </div>
          </Panel>

          <Panel
            title="4 · Generate termination letter"
            eyebrow={isDonna ? 'AI-drafted · Spanish labour-law-compliant · routes to Reports inbox' : 'AI-drafted · Lao Labour Law context · routes to Reports inbox'}
          >
            <div style={{ padding: 14, fontSize: 'var(--t-sm)' }}>
              <p style={{ marginTop: 0, color: 'var(--ink-soft)' }}>
                Click to draft the formal {isDonna ? 'carta de despido' : 'termination letter'}. It lands in the Reports inbox at <code>/h/{propertyId}/inbox</code> for review — copy, forward, or have legal sign off before delivery.
              </p>
              <button
                disabled={!employee || pending}
                onClick={handleGenerate}
                style={{
                  padding: '10px 20px', fontFamily: 'var(--mono)', fontSize: 'var(--t-xs)',
                  letterSpacing: 'var(--ls-extra)', textTransform: 'uppercase',
                  background: 'var(--brass)', color: '#fff',
                  border: 'none', borderRadius: 4, fontWeight: 700,
                  cursor: pending ? 'wait' : 'pointer', opacity: pending ? 0.7 : 1,
                }}
              >
                {pending ? 'Generating…' : 'Generate termination letter'}
              </button>
              {result && (
                <div style={{
                  marginTop: 12,
                  padding: '10px 12px',
                  background: result.ok ? 'rgba(60, 130, 80, 0.08)' : 'rgba(178, 59, 59, 0.08)',
                  border: `1px solid ${result.ok ? 'rgba(60, 130, 80, 0.3)' : 'rgba(178, 59, 59, 0.3)'}`,
                  borderRadius: 4,
                  color: result.ok ? '#3c8250' : '#B23B3B',
                }}>
                  {result.message}
                  {result.ticket_id && (
                    <> · <a href={`/h/${propertyId}/inbox`} style={{ color: 'inherit', fontWeight: 600 }}>Open inbox →</a></>
                  )}
                </div>
              )}
            </div>
          </Panel>
        </>
      )}
    </>
  );
}

function resolveIndem(e: EmployeeWithSeniority, reason: Reason): string {
  const fmt = (n: number | null) => (n && n > 0) ? `€${Math.round(n).toLocaleString('en-US')}` : '—';
  if (reason === 'unfair') return fmt(e.indemUnfair);
  if (reason === 'objective') return fmt(e.indemObjective);
  if (reason === 'fixed_term_end') return fmt(e.indemFixedTermEnd);
  return '— (none)';
}

function SnapshotField({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ padding: '8px 10px', background: 'var(--paper)', border: '1px solid var(--paper-deep)', borderRadius: 4 }}>
      <div style={labelStyle()}>{label}</div>
      <div style={{ marginTop: 3, fontWeight: 600, color: 'var(--ink)' }}>{value}</div>
    </div>
  );
}

function labelStyle(): React.CSSProperties {
  return {
    fontFamily: 'var(--mono)', fontSize: 'var(--t-xs)',
    letterSpacing: 'var(--ls-extra)', textTransform: 'uppercase',
    color: 'var(--ink-mute)',
  };
}

function inputStyle(): React.CSSProperties {
  return {
    padding: '6px 10px', border: '1px solid var(--rule)',
    borderRadius: 4, font: 'inherit', background: 'var(--paper)',
    color: 'var(--ink)',
  };
}
