// app/api/reputation/email-report/route.ts
// PBS 2026-07-06: Send a reputation summary via Resend. Reuses the domain-verified
// info@thenamkhan.com sender from the newsletter engine (task #71).
import { NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabaseAdmin';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface Req {
  to: string;
  subject: string;
  text: string;
  html_bullets: string[];
}

export async function POST(req: Request) {
  let body: Req;
  try { body = await req.json(); }
  catch { return NextResponse.json({ ok: false, error: 'invalid_json' }, { status: 400 }); }

  if (!body.to || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.to)) {
    return NextResponse.json({ ok: false, error: 'invalid_email' }, { status: 400 });
  }

  // Resend key: Vercel env first (that's where the newsletter engine reads it), Vault as fallback.
  let resendKey = process.env.RESEND_API_KEY ?? process.env.RESEND_TOKEN ?? '';
  if (!resendKey) {
    const sb = getSupabaseAdmin();
    const { data: keyData } = await sb.rpc('fn_read_vault_secret', { p_name: 'resend_api_key' });
    resendKey = keyData ? String(keyData) : '';
  }
  if (!resendKey) return NextResponse.json({ ok: false, error: 'resend_key_missing', detail: 'RESEND_API_KEY not set in Vercel env or Vault' }, { status: 500 });

  const html = `<!doctype html><html><body style="font-family: -apple-system, system-ui, sans-serif; color:#1B1B1B; background:#FFFFFF; padding:24px;">
  <h2 style="color:#084838; margin:0 0 12px; font-size:18px;">${escapeHtml(body.html_bullets[0] ?? 'Reputation summary')}</h2>
  <ul style="padding-left:18px; color:#3A3A3A;">
    ${body.html_bullets.slice(1).map(b => `<li style="font-size:13px; line-height:1.55; margin-bottom:6px;">${escapeHtml(b)}</li>`).join('')}
  </ul>
  <p style="font-size:11px; color:#8A8A8A; margin-top:16px;">Generated by Namkhan BI · Guest · Reputation</p>
</body></html>`;

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${resendKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      from: 'The Namkhan · Reputation <info@thenamkhan.com>',
      to: [body.to],
      subject: body.subject,
      text: body.text,
      html,
    }),
  });

  const j = await res.json();
  if (!res.ok) return NextResponse.json({ ok: false, error: 'resend_error', detail: j }, { status: 502 });
  return NextResponse.json({ ok: true, id: j.id });
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, ch => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[ch]!));
}