-- Recovered from supabase_migrations.schema_migrations on 2026-05-06.
-- Version: 20260503170920
-- Name:    seed_calendar_event_types
-- Source:  prod kpenyneooigsyuuomgct (canonical)
-- Method:  supabase db dump --data-only --schema supabase_migrations + parse + split


INSERT INTO marketing.calendar_event_types 
(type_code, display_name, category, default_demand_score, marketing_lead_days_min, marketing_lead_days_max, scrape_lead_days_min, scrape_lead_days_max, default_source_markets, notes)
VALUES
-- =================== HIGHEST DEMAND - LONG LEAD TIMES ===================
('xmas_nye', 'Christmas & New Year', 'religious', 100, 75, 150, 21, 180,
  ARRAY['EU','GB','US','AU','SG','HK'],
  'Highest-demand period. Bookings start 4-5 months out. Marketing teasers begin Sept-Oct, full campaign Nov. Comp scraping critical Oct-Dec.'),

('chinese_ny', 'Chinese New Year', 'national', 95, 60, 120, 21, 150,
  ARRAY['CN','SG','MY','TW','HK','TH'],
  'CNY week + buildup. Source markets are Chinese diaspora. Bookings 2-4 months out. Date varies (lunar).'),

('pi_mai', 'Pi Mai - Lao New Year', 'national', 100, 45, 120, 14, 120,
  ARRAY['LA','TH','EU','US','AU','GB'],
  'Apr 13-15. Largest Lao cultural event. LP becomes peak destination. Often coincides with Songkran TH and Easter West.'),

('songkran_th', 'Songkran (Thai New Year)', 'national', 75, 45, 90, 14, 90,
  ARRAY['TH'],
  'Apr 13-15. Major TH source market driver. Overlaps Pi Mai. Often combined campaign.'),

-- =================== HIGH DEMAND - MEDIUM LEAD ===================
('boun_ok_phansa', 'Boun Ok Phansa - End of Lent', 'religious', 90, 30, 75, 14, 90,
  ARRAY['LA','TH'],
  'Lantern festival in Luang Prabang. Major local cultural event with international interest. Lunar date.'),

('that_luang', 'That Luang Festival', 'religious', 70, 30, 60, 14, 75,
  ARRAY['LA','TH'],
  'November Buddhist festival in Vientiane but draws tourism to LP region.'),

('golden_week_jp', 'Golden Week (Japan)', 'national', 75, 45, 90, 14, 75,
  ARRAY['JP'],
  'Apr 29 - May 5. Major JP outbound holiday. Premium-paying segment.'),

('easter', 'Easter Holiday', 'religious', 75, 30, 75, 14, 75,
  ARRAY['EU','GB','AU','US'],
  'School holidays in EU/GB. Family travel. Lunar (Western calendar).'),

('thai_long_weekends', 'Thai Long Weekends', 'national', 65, 21, 60, 14, 60,
  ARRAY['TH'],
  'Various TH public holidays creating 3-4 day weekends. Drive-market traffic via Chiang Khong border.'),

('vesak', 'Vesak (Buddha Day)', 'religious', 65, 21, 45, 7, 60,
  ARRAY['TH','LK','MM','SG'],
  'Asian Buddhist holiday, varies by lunar calendar.'),

-- =================== SEASONAL CLUSTERS ===================
('summer_peak_west', 'Western Summer Holiday Peak', 'seasonal', 60, 60, 120, 21, 120,
  ARRAY['EU','GB','US','AU'],
  'Jul-Aug. EU/US school summer break. Long stays, premium ADR.'),

('winter_escape_jan', 'January Winter-Escape Travel', 'seasonal', 70, 60, 120, 30, 120,
  ARRAY['EU','GB','US','CA','RU'],
  'Post-NYE through Feb. EU/GB market escapes winter. High-value segment.'),

-- =================== LUNAR / NAMKHAN-SPECIFIC ===================
('full_moon', 'Full Moon (lunar)', 'lunar', 55, 14, 45, 7, 45,
  ARRAY['EU','US','GB','AU','TH'],
  'Monthly. Drives The Namkhan retreat positioning. Full Moon Meditation series content. Tie to wellness segment.'),

('boun_pha_vet', 'Boun Pha Vet (LP Festival)', 'religious', 65, 21, 60, 14, 60,
  ARRAY['LA','TH','EU'],
  'Local LP festival. Cultural-tourism appeal.'),

-- =================== PROPERTY-SPECIFIC ===================
('retreat_anchor_full_moon', 'Anchor Retreat (Full Moon)', 'property', 80, 30, 90, 21, 90,
  ARRAY['EU','GB','US','AU'],
  'The Namkhan retreat program full-moon-anchored. Demand is generated by us, not external.'),

('content_drop', 'Content / YouTube Drop', 'property', 30, 14, 45, 0, 0,
  ARRAY['EU','US','GB'],
  'Grace narrated video drop. Marketing-only, not rate-relevant.'),

-- =================== UNESCO / LP-SPECIFIC ===================
('unesco_anniversary', 'LP UNESCO Anniversary', 'national', 60, 30, 75, 14, 75,
  ARRAY['EU','UNESCO_audience'],
  'Dec 2 - Luang Prabang UNESCO World Heritage status anniversary. Press hook.')
ON CONFLICT (type_code) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  default_demand_score = EXCLUDED.default_demand_score,
  marketing_lead_days_min = EXCLUDED.marketing_lead_days_min,
  marketing_lead_days_max = EXCLUDED.marketing_lead_days_max,
  scrape_lead_days_min = EXCLUDED.scrape_lead_days_min,
  scrape_lead_days_max = EXCLUDED.scrape_lead_days_max,
  default_source_markets = EXCLUDED.default_source_markets,
  notes = EXCLUDED.notes;
