-- Recovered from supabase_migrations.schema_migrations on 2026-05-06.
-- Version: 20260503180143
-- Name:    flag_rules_engine
-- Source:  prod kpenyneooigsyuuomgct (canonical)
-- Method:  supabase db dump --data-only --schema supabase_migrations + parse + split


-- ============================================================
-- TABLE: flag_rules — the rule catalog (RM-editable)
-- One row per flag rule. Active rules run on every agent run.
-- ============================================================
CREATE TABLE IF NOT EXISTS revenue.flag_rules (
  rule_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_code TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  dimension TEXT NOT NULL CHECK (dimension IN ('rate','rate_plan','promo','ranking','reviews','window','los','self')),
  description TEXT,
  
  -- Threshold config
  threshold_type TEXT NOT NULL CHECK (threshold_type IN ('absolute_pct','absolute_value','baseline_deviation_pct','baseline_deviation_abs','presence','transition')),
  threshold_value NUMERIC,             -- e.g. 15.0 for "15% change"
  threshold_value_2 NUMERIC,           -- second threshold for ranges
  baseline_window_days INT DEFAULT 14, -- look back this many days for baseline
  
  -- Severity tiering
  severity_default TEXT NOT NULL CHECK (severity_default IN ('info','low','medium','high','critical')),
  -- Auto-escalate to higher severity if event-tagged date
  escalate_on_event BOOLEAN DEFAULT true,
  
  -- Suggested action
  suggested_action TEXT NOT NULL CHECK (suggested_action IN ('monitor','investigate','consider_matching','match_now','review_strategy','ignore')),
  action_text TEXT,                    -- pre-formatted action prompt
  
  -- Lifecycle
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID
);

CREATE INDEX idx_flag_rules_dim ON revenue.flag_rules(dimension, is_active);
ALTER TABLE revenue.flag_rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "flag_rules_read" ON revenue.flag_rules FOR SELECT USING (true);
CREATE POLICY "flag_rules_write" ON revenue.flag_rules FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- TABLE: flags — flag instances generated by rules
-- One row per flag firing. Status managed by RM (open / acknowledged / dismissed / resolved)
-- ============================================================
CREATE TABLE IF NOT EXISTS revenue.flags (
  flag_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_id UUID REFERENCES revenue.flag_rules(rule_id),
  rule_code TEXT NOT NULL,
  
  -- Subject
  comp_id UUID REFERENCES revenue.competitor_property(comp_id),
  property_name TEXT,
  channel TEXT,
  stay_date DATE,
  taxonomy_code TEXT,
  
  -- Detection
  detected_at TIMESTAMPTZ DEFAULT NOW(),
  detected_by_run_id UUID REFERENCES governance.agent_runs(run_id),
  
  -- Values
  observed_value NUMERIC,
  baseline_value NUMERIC,
  delta_value NUMERIC,
  delta_pct NUMERIC,
  
  -- Context
  severity TEXT NOT NULL CHECK (severity IN ('info','low','medium','high','critical')),
  event_context TEXT[],                -- ['vesak','full_moon'] if stay_date overlaps event
  is_event_escalated BOOLEAN DEFAULT false,
  
  -- Pre-formatted display
  flag_label TEXT NOT NULL,            -- "Sofitel dropped 18% vs 14d baseline"
  suggested_action TEXT,
  action_text TEXT,
  
  -- Workflow
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','acknowledged','dismissed','resolved','expired')),
  resolved_at TIMESTAMPTZ,
  resolved_by UUID,
  resolution_note TEXT,
  
  -- Lineage
  raw_data JSONB,                      -- the rates/rankings rows that triggered this
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_flags_status ON revenue.flags(status, severity, detected_at DESC);
CREATE INDEX idx_flags_comp ON revenue.flags(comp_id, status);
CREATE INDEX idx_flags_run ON revenue.flags(detected_by_run_id);

-- Auto-expire flags after 14 days if still open
CREATE OR REPLACE FUNCTION revenue.fn_expire_old_flags() RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  UPDATE revenue.flags 
  SET status = 'expired'
  WHERE status = 'open' 
    AND detected_at < NOW() - INTERVAL '14 days';
END $$;

ALTER TABLE revenue.flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "flags_read" ON revenue.flags FOR SELECT USING (true);
CREATE POLICY "flags_write" ON revenue.flags FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- Seed default rules (the catalog you'd normally curate over months)
-- ============================================================
INSERT INTO revenue.flag_rules (rule_code, display_name, dimension, description, 
  threshold_type, threshold_value, threshold_value_2, baseline_window_days,
  severity_default, escalate_on_event, suggested_action, action_text) VALUES

-- ===================== RATE =====================
('rate_comp_drop_significant', 'Comp dropped rate vs baseline', 'rate',
  'A competitor drops their rate by X% vs their own 14-day average for the same stay date.',
  'baseline_deviation_pct', -10, NULL, 14,
  'medium', true, 'investigate',
  'Check if this is a one-off or sustained. If event-tagged date, consider matching pace.'),

('rate_comp_drop_aggressive', 'Comp aggressively dropped rate', 'rate',
  'A competitor drops their rate by 20%+ vs their own baseline.',
  'baseline_deviation_pct', -20, NULL, 14,
  'high', true, 'consider_matching',
  'Significant move. Review pickup, then consider matching or holding firm with packaging.'),

('rate_comp_spike', 'Comp raised rate vs baseline', 'rate',
  'A competitor raised their rate by 15%+ vs their own baseline. May indicate they see demand we''re missing.',
  'baseline_deviation_pct', 15, NULL, 14,
  'low', true, 'investigate',
  'Check pickup data — comp may have signal we don''t. Consider raising if our pickup is also strong.'),

('rate_we_below_median_far', 'We are far below comp median', 'self',
  'Our rate is 15%+ below the comp set median for the same stay date. Possible underpricing.',
  'baseline_deviation_pct', -15, NULL, 1,
  'medium', true, 'review_strategy',
  'Verify intentional. Pi Mai / NYE we should NOT lead the market down.'),

('rate_we_above_median_far', 'We are far above comp median', 'self',
  'Our rate is 20%+ above comp median. Risk of losing share to comps without strong differentiation.',
  'baseline_deviation_pct', 20, NULL, 1,
  'medium', false, 'review_strategy',
  'Confirm pickup is holding. If not, consider repositioning or stronger packaging.'),

('rate_parity_break', 'Direct rate higher than OTA', 'self',
  'Our direct rate is HIGHER than the cheapest OTA — parity violation hurts direct conversion.',
  'absolute_value', 0, NULL, 1,
  'high', false, 'match_now',
  'Direct must be ≤ OTA. Fix in Cloudbeds or check rate plan setup.'),

-- ===================== RATE PLAN =====================
('plan_new_appearance', 'Comp launched new rate plan', 'rate_plan',
  'Plan taxonomy code seen for first time on competitor in last 14 days.',
  'transition', NULL, NULL, 14,
  'medium', false, 'investigate',
  'New plan type means new strategy. Check if we should match (Early Bird etc).'),

('plan_disappearance', 'Comp removed a rate plan', 'rate_plan',
  'Plan that was offered last week is no longer visible this week.',
  'transition', NULL, NULL, 7,
  'low', false, 'monitor',
  'May indicate inventory changes or strategic shift.'),

('plan_gap_high_coverage', 'Comp set offers a plan we don''t', 'rate_plan',
  'A plan type is offered by 50%+ of competitors but not by us.',
  'baseline_deviation_pct', 50, NULL, 14,
  'medium', false, 'review_strategy',
  'Significant gap. Evaluate adding this plan type to compete.'),

-- ===================== PROMO =====================
('promo_started_aggressive', 'Comp started aggressive promo', 'promo',
  'Comp begins promo with discount ≥20%.',
  'absolute_pct', 20, NULL, 1,
  'high', true, 'investigate',
  'Aggressive market move. Check duration and which dates targeted. Consider response.'),

('promo_burst_detected', 'Flash burst pattern detected', 'promo',
  'Comp ran 5–10 days of promo with peak ≥20%. Suggests reactive flash response to demand softness.',
  'transition', NULL, NULL, 14,
  'medium', false, 'monitor',
  'Likely flash response. Watch for repeat pattern.'),

('promo_pattern_change', 'Comp promo pattern changed', 'promo',
  'Comp transitioned from one promo pattern to another (e.g. occasional → sustained_aggressive).',
  'transition', NULL, NULL, 30,
  'medium', false, 'investigate',
  'Strategic change. Investigate cause — soft pickup, new GM, OTA push?'),

-- ===================== RANKING =====================
('ranking_drop_significant', 'Ranking dropped 3+ positions', 'ranking',
  'Property dropped 3 or more positions on OTA search results vs last week.',
  'baseline_deviation_abs', 3, NULL, 7,
  'medium', false, 'investigate',
  'Possible content / review / inventory issue. Check OTA dashboard.'),

('ranking_off_first_page', 'Fell off first page', 'ranking',
  'Property was on page 1 last week, now on page 2+.',
  'transition', NULL, NULL, 7,
  'high', false, 'investigate',
  'First-page exit hurts visibility significantly. Diagnose immediately.'),

('ranking_new_badge', 'New badge / tier on competitor', 'ranking',
  'Competitor gained Genius / Preferred / Sponsored / Top-rated badge.',
  'transition', NULL, NULL, 7,
  'low', false, 'monitor',
  'May affect their conversion. Watch for downstream pickup shifts.'),

-- ===================== REVIEWS =====================
('review_score_drop', 'Review score dropped', 'reviews',
  'Property review score fell by 0.3+ on any single channel.',
  'baseline_deviation_abs', -0.3, NULL, 30,
  'medium', false, 'investigate',
  'Recent guest issue. If our review, address recovery. If competitor, opportunity to take share.'),

('review_velocity_spike', 'Review count surged', 'reviews',
  'Review count jumped 50%+ vs prior period — high recent volume.',
  'baseline_deviation_pct', 50, NULL, 30,
  'low', false, 'monitor',
  'High recent activity. Could be group, event, or PR moment.'),

-- ===================== WINDOW / LEAD TIME =====================
('window_close_in_pressure', 'Close-in pricing pressure', 'window',
  'At T+3 to T+14, comp set median dropped 10%+ vs T+30 levels — close-in softness.',
  'baseline_deviation_pct', -10, NULL, 14,
  'medium', true, 'investigate',
  'Market softening close-in. Check our pickup pace before holding firm.'),

('window_advance_purchase_appears', 'Comp added Advance Purchase plan', 'window',
  'Non-refundable + advance purchase plan appeared where it wasn''t before.',
  'transition', NULL, NULL, 14,
  'medium', false, 'investigate',
  'New booking-window strategy. Evaluate adding similar.'),

-- ===================== LOS =====================
('los_min_restriction_added', 'Comp added min-LOS restriction', 'los',
  'Min-LOS appeared on dates that previously had none. Often signals expected high demand.',
  'transition', NULL, NULL, 14,
  'low', true, 'monitor',
  'Comp expects strong demand. Consider mirroring restriction on peak dates.'),

('los_promo_los_appears', 'Length-of-stay promo launched', 'los',
  'Stay 3+ / Stay 5+ promo seen for first time in 14 days.',
  'transition', NULL, NULL, 14,
  'low', false, 'monitor',
  'New LOS-based discount. Consider matching for direct.')

ON CONFLICT (rule_code) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  threshold_value = EXCLUDED.threshold_value,
  severity_default = EXCLUDED.severity_default,
  suggested_action = EXCLUDED.suggested_action,
  action_text = EXCLUDED.action_text,
  updated_at = NOW();
