-- Recovered from supabase_migrations.schema_migrations on 2026-05-06.
-- Version: 20260506190002
-- Name:    phase_1a_kb_entries_and_cron_staleness
-- Source:  prod kpenyneooigsyuuomgct (canonical)
-- Method:  supabase db dump --data-only --schema supabase_migrations + parse + split

-- Phase 1A — 3 KB entries + weekly staleness cron + Felix/Data/Sage prompt routing notes.
-- Author: PBS via Claude (Cowork) · 2026-05-06.

-- 3 KB entries
INSERT INTO public.cockpit_knowledge_base (topic, key_fact, scope, source, confidence, active) VALUES
('reference library exists — query before guessing',
 'All agents MUST call query_reference_library BEFORE answering questions about external systems (Cloudbeds, Make, Supabase, Vercel, GitHub, Anthropic, Resend, etc). If no entry exists, route the request to Atlas Anders (api_specialist) who creates one. Never pull external-system facts from training data alone — the library is canonical.',
 'global', 'system', 'high', true),
('credentials never stored in reference_library',
 'reference_sources.credentials_location stores ONLY the pointer (vault name, env var name like "Vercel env: ANTHROPIC_API_KEY"). Actual credentials live in Vercel env / Supabase secrets / 1Password. Atlas Anders MUST never store API keys or tokens in any reference_library column. Hard rule: any reviewer who sees a credential in the table opens a P0 incident.',
 'global', 'system', 'high', true),
('staleness threshold defaults to 90 days',
 'reference_sources.staleness_days_threshold defaults to 90. Override per-source for fast-moving APIs: Anthropic API = 30 (releases monthly), Supabase = 30 (frequent advisor changes), Vercel = 30 (frequent CLI/UI changes), Cloudbeds = 60 (semiannual API updates), GitHub = 60. Weekly cron flags stale entries; Atlas Anders processes the queue.',
 'global', 'system', 'high', true);

-- Weekly staleness cron — Mondays 06:00 UTC
SELECT cron.schedule(
  'reference_library_staleness_check',
  '0 6 * * 1',
  $cron$
    -- Insert one cockpit_ticket per stale source for Atlas Anders.
    INSERT INTO public.cockpit_tickets (source, arm, intent, status, email_subject, parsed_summary, notes)
    SELECT
      'cron_staleness',
      'research',
      'investigate',
      'triaged',
      '[atlas] Stale reference: ' || s.system_name,
      'Reference library entry "' || s.system_name || '" last verified '
        || COALESCE(to_char(s.last_verified_at, 'YYYY-MM-DD'), 'never')
        || ' (threshold: ' || s.staleness_days_threshold || ' days). Atlas should fetch '
        || s.canonical_url || ', compare against stored summary + key_facts, then call '
        || 'verify_reference_entry (if unchanged) or update_reference_entry (if changed).',
      'Auto-generated by reference_library_staleness_check cron (Mondays 06:00 UTC).'
    FROM public.reference_sources s
    WHERE s.status = 'active'
      AND (
        s.last_verified_at IS NULL
        OR s.last_verified_at < NOW() - (s.staleness_days_threshold * INTERVAL '1 day')
      )
      AND NOT EXISTS (
        -- Skip if there's already an open ticket for this source
        SELECT 1 FROM public.cockpit_tickets t
        WHERE t.email_subject = '[atlas] Stale reference: ' || s.system_name
          AND t.status NOT IN ('completed','closed','triage_failed')
      );
  $cron$
);

-- KB entry confirming the cron + agent are live
INSERT INTO public.cockpit_knowledge_base (topic, key_fact, scope, source, confidence, active) VALUES
('Phase 1A reference_library shipped 2026-05-06',
 'Phase 1A complete: 3 tables (reference_sources / reference_entries / reference_audit_log) + RLS + DELETE-prevention triggers; Atlas Anders (api_specialist) agent live with 4 skills (query_reference_library, create_reference_source, update_reference_entry, verify_reference_entry); 8 sources seeded (Cloudbeds, Cloudbeds Insights, Supabase, Vercel, GitHub, Anthropic API, Make.com, Resend) with 22 starter entries; query_reference_library granted to all 14 active agents; weekly staleness cron at Mondays 06:00 UTC. ADR: cockpit/decisions/0006-reference-library.md. UI: /cockpit/docs-registry (file written to disk, awaits commit + deploy).',
 'global', 'system', 'high', true);